blog/urls.py
from django.urls import path
# import url
from django.conf.urls import url
from . import views
urlpatterns = [
    # home page
    path('', views.index, name='index'),

    # Topics Page
    path('Topics/', views.topics, name='topics'),

    # Detail page for a single topic

    url(r'^Topics/(?P<topic_id>\d+)/$', views.topic, name='topic'), 

    # Page for adding a new topic
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

    # Page for adding a new entry       #<------------->
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # Page for editing an entry
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

    # Page for adding a download  <--------
    url(r'^(?P<fileupload_id>\d+)/download_file/$', views.download_file, name='download_file'),

    
]

users/urls.py
"""Defines URL patterns for users"""
from django.http import HttpResponseRedirect
from django.contrib.auth import logout, login
from django.urls import path
# import url
from django.conf.urls import url
from . import views
app_name='users'
urlpatterns = [
    # home page
    #path('', views.index, name='index'),
    # login Page
    path('login/', views.loginreq, name='login'),

   # logout page
    path("logout", views.logout_request, name="logout"),

   # Registration page
    path("register/", views.register, name="register"),
]

website1/urls.py
from django.contrib import admin
from django.urls import path, include
#from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
    #url(r'^users/', include('users.urls')),
] 

#< + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
#from .models import Fileupload
from .validators import validate_file_size, validate_file_extension
# Create your models here.

class Topic(models.Model):
    """A topic the user is learning about"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """Something specific learned about a topic"""
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    # fileupload = models.ForeignKey(Fileupload, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    def __str__(self):
        """Return a string representation of the model."""
        return self.text
    
    
    # model for file uploading
class Fileupload(models.Model):
    entry = models.ForeignKey(Entry, null=True, on_delete=models.PROTECT)
# file will be uploaded to MEDIA_ROOT/uploads
    upload = models.FileField(upload_to='uploads/', validators=[validate_file_size , validate_file_extension])
   
    def upload_link(self):
        if self.upload:
            return "<a href='%s'>download</a>" % (self.upload.url)
        else:
            return "No Attachment"
        upload_link.allow_tags = True
    
    

blog/forms.py
from django import forms
from .models import Topic, Entry, Fileupload
from .validators import validate_topic, validate_char
# from django.core.validators import
from django.core.exceptions import ValidationError
from .forms import ValidationError


class TopicForm(forms.ModelForm):
    #text=forms.ModelChoiceField(label="Choice list",queryset=Topic.objects.all())  #<-----
    text=forms.CharField(label='Title', error_messages={"required":"Topic should be descriptive enough & unique, at least 3 words long!"}, validators=[validate_topic, validate_char],) #<---------
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

         

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}
        
class FileuploadForm(forms.ModelForm):
    class Meta:
        model = Fileupload
        fields = ['upload']
        upload = forms.FileField(widget=forms.ClearableFileInput(attrs={'accept': 'application/pdf'}))
    # upload = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

blog/views.py
from __future__ import unicode_literals
from django.shortcuts import render , get_object_or_404, render_to_response
from django.http import HttpResponseRedirect, Http404
#from django.core.urlresolver import reverse
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry, Fileupload
from .forms import TopicForm, EntryForm, FileuploadForm 
#from .forms import ModelFormWithFileField
from django.conf import settings
from django.contrib import messages
# for download
import os
from django.http import FileResponse
from django.template import RequestContext
#from django.conf.urls.static import static
from django.contrib.staticfiles.templatetags.staticfiles import static
# Create your views here.

def index(request):
    """The home page for Learning Log"""
    return render(request, 'index.html')

#@login_required
def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    
    # Restricting Topics Access to Appropriate Users
    #topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'topics.html', context)

#@login_required
def topic(request, topic_id):
    """Show a single topic and all its entries."""
    topic = Topic.objects.get(id=topic_id)
    #---------------------------------------------
    entry, created = Entry.objects.get_or_create(topic_id=(topic.id), text='Hi!-default entry, to upload file click add new entry' )
    entry_id=entry.id
    fileupload, created = Fileupload.objects.get_or_create(entry_id=(entry.id), upload='uploads/About_us.pdf')   #<--'/media/uploads/Application.pdf'
    #-----------------------------------------------
    # try:
    #     entry=Entry.objects.get(id=topic_id)
    #     entry_id=entry.id 
        
    # #     # show Fileupload objects
    # except Entry.DoesNotExist:
    #     entry = Entry(topic_id=(topic.id), text='Hi!-default entry, to upload file click add new entry' )
    #     entry.save()  
    #     entry_id=entry.id   #<-------
    # try:
    #   fileupload=Fileupload.objects.get(id=entry_id)S
    # except Fileupload.DoesNotExist:
    #     fileupload=Fileupload(entry_id=(entry.id), upload='/media/uploads/Application.pdf' )   #<------
    #     fileupload.save()      
    #---------------------------------------------
    #entry = Entry.objects.create(topic_id=(topic.id), text='Hi' )
    #----------------------------------------------      
    #fileupload=Entry.objects.get(id=topic_id) 
    # Protecting a User’s Topics
    #if topic.owner != request.user:
        #raise Http404("Invalid user")
    
    entries = topic.entry_set.order_by('-date_added')
    #ufiles=fileupload.upload_link()  
    ufiles = entry.fileupload_set.order_by('id')
    
    context = {'topic': topic, 'entries': entries,'ufiles': ufiles}
    return render(request, 'topic.html', context)

@login_required
def new_topic(request):
    """Add a new topic."""
    topic = Topic.objects.all()
    form=TopicForm(request.POST)
    if request.method=='POST':
        #------------------
        if form.is_valid():
            text= form.cleaned_data.get("text")
            if form.cleaned_data["text"]:
                topic=topic.filter(text__icontains=form.cleaned_data["text"])
                if not(topic): #<----
                    new_topic = form.save(commit=False)
                    new_topic.owner = request.user
                    new_topic.text=text.title()  #<-------
                    new_topic.save()
                    
                else:
                    
                    raise Http404("Topic already exist: Title should be unique!")
                    
            form.save()
        else:
            raise Http404("Invalid Data: Title must begin with alphabets & should be descriptive enough!")
        return HttpResponseRedirect('/Topics')
        #------------------
        select_topic=get_object_or_404(Topic,pk=request.POST.get('topic_id'))
        topic.text=select_topic
        topic.save()
    #return render_to_response('new_topic.html', {'topic':topic}, context_instance = RequestContext(request))
    context = { 'form': form ,'topic':topic }
    return render(request, 'new_topic.html', context)
    
    # topic = Topic.objects.all()
    # if (request.method) != 'POST':
    # #     # No data submitted; create a blank form.
    #     form = TopicForm() #-------
        
    # else:
         
    #     form = TopicForm(request.POST)
    #     if form.is_valid():
    #          #----------------------------
    #         text= form.cleaned_data.get("text")
    #         if form.cleaned_data["text"]:
    #             topic=topic.filter(text__icontains=form.cleaned_data["text"])
    #          #----------------------------                   
    #         #text= form.cleaned_data.get('text')
               
    #         # Associating New Topics with the Current User
    #         #topic = Topic.objects.filter(text=request.POST['text'])
            
    #             if not(topic): #<----
    #                 new_topic = form.save(commit=False)
    #                 new_topic.owner = request.user
    #                 new_topic.save()
    #             else:
    
    #                 raise Http404("Topic already exist")
    
    #     form.save()
    #     return HttpResponseRedirect('/Topics')
                   
    # context = { 'form': form ,'topic':topic }
    # return render(request, 'new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Add a new entry for a particular topic."""
    topic = Topic.objects.get(id=topic_id)
    #<------------------------------------
    entry=Entry.objects.get(id=topic_id)  #<--------
    
    #topic=entry.topic
    #fileupload=Fileupload.objects.get(id=entry_id)
    
    #<-------------------------------------
    # prevent unauthorised entry
    if topic.owner != request.user:
        raise Http404("Invalid user,you are not authhorised user")
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
        # File upload blank form
        form_up=FileuploadForm()  #<-------
    else:
       # POST data submitted; process data.
        form = EntryForm(data=request.POST)
        # upload form
        form_up=FileuploadForm(data=request.POST, files=request.FILES)   #<---------
        if (form.is_valid() and form_up.is_valid()): 
             
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            form.save()
            #-----------------------------------------------
        #if form_up.is_valid():
            new_file=form_up.save(commit=False)
            new_file.entry=entry
            new_file.save()
            form_up.save()
            #-----------------------------------------------
                       
            return HttpResponseRedirect('/Topics')
                                       
    context = {'topic': topic, 'form': form, 'form_up': form_up}
    return render(request, 'new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Edit an existing entry."""
    entry = Entry.objects.get(id=entry_id)
    #fileupload=Fileupload.objects.all() #<---here change
    topic = entry.topic
    #Protecting the edit_entry Page
    if topic.owner != request.user:
        raise Http404("Invalid user,you are not authhorised user")

    if request.method != 'POST':
    #     # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
        # form_up=FileuploadForm(fileupload) #<---here change
    else:
        # POST data submitted; process data.
    
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            #edit_entry.save()
            return HttpResponseRedirect('/Topics')

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'edit_entry.html', context)

# Function for download

@login_required
def download_file(request, fileupload_id):
    fileupload = get_object_or_404(Fileupload, pk=fileupload_id)  #<------

    file_name, file_extension = os.path.splitext(fileupload.upload.file.name)
    file_extension = file_extension[1:] # remove the dot
    response = FileResponse(fileupload.upload.file, content_type="file/%s" % file_extension)
    response["Content-Disposition"] = "attachment;" \
        "filename=%s.%s" % (fileupload.upload.name[:50] , file_extension[:50])
    return response

blog/templates/base.html
{% load staticfiles %}
{% load bootstrap4 %}
{% comment %}
<p>
  <!--new added for site logo-->
  <img src="{% static "images\sitelogo.png" %}" alt="Logo" />
  <!--<img src="{{ MEDIA_URL }} \media\uploads\sitelogo.png" /> -->
  <a href="{% url 'index' %}">Learning Tracker</a> -
  <a href="{% url 'topics' %}">Topics</a> -
  {% if user.is_authenticated %}
    Hello, {{ user.username }}
  <a href="{% url 'users:logout' %}">log out</a>
  {% else %}
    <a href="{% url 'users:register' %}">register</a> -
    <a href="{% url 'users:login' %}">log in</a>
    
  {% endif %}
  
</p>

{% block content %}{% endblock content %}
{% endcomment %}

<!--       Styling App -new code for base.html           -->



<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
    shrink-to-fit=no">
    <title>Learning Tracker</title>
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    
  </head>
  <body>
    
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">
      <img src="{% static "images\sitelogo.png" %}" alt="Logo" />
      <a class="navbar-brand" href="{% url 'index'%}">-Learning Tracker</a>
      
      <button class="navbar-toggler" type="button" data-toggle="collapse"\
        data-target="#navbarCollapse" aria-controls="navbarCollapse"\
        aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
            <a class="nav-link" href="{% url 'topics'%}">Topics</a>
            
            </li>
        </ul>

        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <span class="navbar-text"}">Hello, {{ user.username }}.</span>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Register</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Log in</a>
            </li>
            {% endif %}
        </ul>
      </div>


    </nav>
    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>
    <!--new for footer
    <footer class="footer">
      <div class="container">
      <span class="text-muted">
      © Learning Tracker 2020
      </span>
      </div>
    </footer> -->
  </body>
</html>

blog/templates/edit_entry.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block page_header %} <!-- BS4-->
    <h3>Edit entry:</h3> <!-- BS4-->
{% endblock page_header %} <!-- BS4-->

{% block content %}

<p><h3><a href="{% url 'topic' topic.id %}">Title:{{ topic }}</a></h3></p>
<!--<p>Edit entry:</p> -->

<form action="{% url 'edit_entry' entry.id %}" method='post' class="form">
{% csrf_token %}
{% bootstrap_form form %} <!--{{ form.as_p }} -->
{% buttons %}
<button name="submit" class="btn btn-primary">save changes</button>
{% endbuttons %}
</form>
{% endblock content %}

blog/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<div class="jumbotron">            <!--new added-->
<p class="lead">Learning Tracker helps you keep track of your learning. Once logged in user can create new topic,
add/edit new entry, upload/read/download pdf for any topic you are learning about. 
{% if not user.is_authenticated %}

<strong><a href="{% url 'users:login' %}">Registered user pls. Log in</a></strong>
</p>
<a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
role="button">new user? Register &raquo;</a>

{% endif %}


<!--{% load staticfiles %} -->
<!--<div> -->

    <img src="{% static "images\cricket.jpg" %}" alt="Background Picture" />

<!--</div> -->
</div>

<!--new for footer -->
    <footer class="footer">
      <div class="container">
      <span class="text-muted">
      © Learning Tracker 2020
      </span>
      </div>
    </footer>
{% endblock content %}

<!-- image display-->

blog/templates/new_entry.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block page_header %} <!-- BS4-->
    <h3>Add new entry(abstract/description):</h3> <!-- BS4-->
{% endblock page_header %} <!-- BS4-->

{% block content %}

<p><h3><a href="{% url 'topic' topic.id %}">Title:{{ topic }}</a></h3></p>
<!--<p>Add a new entry(abstract/description):</p> -->
<form action="{% url 'new_entry' topic.id %}" method='post' enctype='multipart/form-data' class="form">
{% csrf_token %}
{% bootstrap_form form %} <!--{{ form.as_p }} -->
{{ form_up.as_p }}
{% buttons %}
<button name='submit' class="btn btn-primary">add/upload-entry</button>
{% endbuttons %}
</form>

{% endblock content %}

blog/templates/new_topic.html
{% extends "base.html" %}
{% load bootstrap4 %}
{% block page_header %} <!-- BS4-->
    <h3>Add new topic:</h3> <!-- BS4-->
{% endblock page_header %} <!-- BS4-->

{% block content %}
    <!--<p>Add a new topic:</p> -->
    
    <form action="{% url 'new_topic' %}" method='post' class="form">
        {% csrf_token %}
        
        {% bootstrap_form form %}    <!--{{ form.as_p }} -->
        
        
        <select name="topic_id">
        <option value="">---e.g. refer topic used:---</option>
        {% for t in topic %}
        <option value="{{t.id}}">{{t.text}}</option>
        {% endfor %}
        </select>
        <p>
        {% buttons %}
        <button name="submit" class="btn btn-primary">add topic</button>
        {% endbuttons %}
        </p>
    </form>
    
{% endblock content %}

blog/templates/terms.html
{% extends "base.html" %}

{% block content %}


<p>terms & conditions:</p>

<!--?<a href="{% url 'download_file' fileupload.id %}">{{ufiles}}</a> -->

{% endblock content %}

blog/templates/topic.html
{% extends 'base.html' %}
{% block page_header %} <!-- BS4-->
    <h3>{{ topic }}</h3> <!-- BS4-->
{% endblock page_header %} <!-- BS4-->

{% block content %}

    <!--<p>Topic: {{ topic }}</p> -->
    <!--<p>Entries:</p> -->

    <p>
        <a href="{% url 'new_entry' topic.id %}">add new entry</a>
    </p>
    
    <ul>
    {% for entry in entries %}
        {% if forloop.revcounter0 > 0 %}
        <!--<li>-->
        <div class="card mb-3"> <!--BS4-->
            <h5 class="card-header">  <!--BS4-->  
            <p>{{ entry.date_added|date:'M d, Y H:i' }}
            <small><a href="{% url 'edit_entry' entry.id %}">edit entry</a></small>
            </p>
            </h5> <!--BS4-->
            <div class="card-body">
            <p>{{ entry.text|linebreaks }}</p>
            </div>
            <!--
            <p>
                <small><a href="{% url 'edit_entry' entry.id %}">edit entry</a></small>
            </p>
            -->
        </div>    
        <!--</li> -->   
        {% endif %}
        
    {% empty %}
        <li>
        There are no entries for this topic yet.
        </li>
    {% endfor %}
    <div>
    <p> (click add new entry- to add new description/upload pdf)  </p>
    <p> <strong> Download pdf-study material,notes,books etc. </strong> </p>
    
    {% for entry in entries %}
       
        {% if forloop.revcounter0 == 0 %}
        <a href="{% url 'download_file' entry.id %}"> About Us </a>
        {% else %}
            {% if entries %}
                <p>
                <a href="{% url 'download_file' entry.id %}"> download file:{{ topic }}{{ forloop.revcounter0 }} </a>
                {# fname.upload.url   ufiles|first  #}
                </p>
            {% else %}     
        
                <p> Empty Set-no files to download</p>
            {% endif %}     
        {% endif %}    
        
    {% endfor %}
    </div>
    
    </ul>

    {% endblock content %}

blog/templates/topics.html
{% extends "base.html" %}
{% block page_header %} <!-- BS4-->
  <h2>Topics</h2>   <!-- BS4-->
{% endblock page_header %}  <!-- BS4-->

{% block content %}

  <!--<p>Topics</p>-->
  <ul>
    {% for topic in topics %}
        <li><h4>
            <a href="{% url 'topic' topic.id %}">{{topic}}----Published by {{topic.owner}}</a>
          </h4>    
        </li>
    {% empty %}
        <li><h4>No topics have been added yet.</h4></li>
    {% endfor %}
  </ul>
  <h4><a href="{% url 'new_topic' %}">Add a new topic:</a></h4>
{% endblock content %}